package com.lavaflow.auth.entity;

import com.lavaflow.common.entity.BaseEntity;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Opaque refresh token stored in the database.
 * The token value is a 64-character random hex string generated by JwtService.
 * Rotation strategy: every refresh rotates the token (old one is revoked, new one issued).
 */
@Entity
@Table(name = "refresh_tokens")
@Getter
@Setter
@NoArgsConstructor
public class RefreshToken extends BaseEntity {

    @Column(nullable = false, unique = true, length = 700)
    private String token;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @Column(name = "expiry_date", nullable = false)
    private LocalDateTime expiryDate;

    @Column(nullable = false)
    private boolean revoked = false;

    @Column(name = "replaced_by_token", length = 700)
    private String replacedByToken;

    public boolean isExpired() {
        return LocalDateTime.now().isAfter(expiryDate);
    }
}
