-- Baseline migration for the existing database state.
-- This project also relies on Hibernate ddl-auto=update for schema evolution.
-- The migration is intentionally kept harmless so it can be marked as applied
-- on databases that were already initialized manually before Flyway was enabled.
